### ISSUE TITLE
Consolidating Atom/Modelica packages

### ISSUE THREAD

**Issue by tshort** [modelica-tools/atom-language-modelica#9] opened 2015-10-13 18:12 UTC
Pinging @lochel, @raphaelchenouard, and @thorade.

Hi everyone, it looks like there are several Modelica packages available. The packages by Raphael and Matthis are registered. I've added a couple of features (toggling annotations and a doc view) to Lennart's repo that was forked from Raphael's:

https://github.com/tshort/atom-language-modelica

Can we get these down to one preferred package registered with Atom?

**Comment by bilderbuchi** [comment] 2015-10-13 19:35
consolidation would be great! I don't think @raphaelchenouard maintains this addon anymore, I have had an issue open here since last year. we can also get the help of some atom folks if we need deprecation of a specific addon/fork in favour of another in the atom package index.

**Comment by lochel** [comment] 2015-10-13 19:59
Sounds good to me!

**Comment by thorade** [comment] 2015-10-13 22:00
Sounds good. Maybe having the consolidated package in a somewhat official repository would also be nice, something like modelica-3rdparty/atom-language-modelica
Related: https://discuss.atom.io/t/language-already-defined/15837

My package is based on the Sublime Text grammar by @BorisChumichev using an automatic conversion first to a TextMate grammar, then to Atom grammar:
https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843
So I did not have much work with this and I know too little about grammar to write one from scratch.
The conversion process seems to work quite well; I like that writing one good grammar for Sublime results in a grammar for Sublime, TextMate and Atom.

Boris' package is currently used for syntax highlighting here on github:
https://github.com/github/linguist/issues/2053
But it could as well be based on any TextMate or Atom compatible grammar.

**Comment by thorade** [comment] 2015-10-13 22:03
@tshort I like your documentation view!

**Comment by tshort** [comment] 2015-10-13 23:53
@dietmarw, in this GitHub thread, we've been discussing options for consolidating packages for Modelica support in the Atom text editor. I'm interested if you have any suggestions. The [Modelica tools](https://github.com/modelica-tools) organization looks like it might be suitable for hosting a consolidated Modelica package for Atom.

**Comment by dietmarw** [comment] 2015-10-14 06:06
@tshort yes looking at the discussion I think the Modelica tools organization would be the right place for a tool(extension) like this. Question is how to proceed. Shall I simply for your repo or would you like to move it?

**Comment by raphaelchenouard** [comment] 2015-10-14 07:51
Hi all,

I agree with your proposition. I've only a few time to maintain my atom
package. The documentation view is a nice feature i would have implemented,
but i had no time since now.

Best regards,
Raphael.

2015-10-14 8:06 GMT+02:00 Dietmar Winkler notifications@github.com:

**Comment by thorade** [comment] 2015-10-14 07:56
We also need some more testing of the grammar, the grammar by Raphael had some issues (that was the reason why I ever started on a new grammar) and some are still present in Tom's version.

Here is one example that fails: 
http://bit.ly/1OvL3Rh
while the same with Boris' grammar or my converted grammar works fine:
http://bit.ly/1jy4b3X

The simpler code samples in the linguist repo do all work satisfactory though:
https://github.com/github/linguist/tree/master/samples/Modelica

**Comment by raphaelchenouard** [comment] 2015-10-14 08:10
Ok, thanks Matthis for your feedback.

I'll see if I can have a look to my grammar and solve the problem. I hope
i'll have time in a few days.

@Matthis: If I remember well, you proposed a commit that had solved some
issues and I was thinking all was fine after that.

Regards,
Raphael.

2015-10-14 9:56 GMT+02:00 Matthis Thorade notifications@github.com:

**Comment by thorade** [comment] 2015-10-14 08:18
Sorry Raphael, I should have filed more issues to make it more clear.
The PR I once proposed to you only enabled Lightshow usage.

Here is a shorter example that also fails:
http://bit.ly/1Mz0tTt  versus  http://bit.ly/1LaAyyZ
Looks like a semicolon inside `<pre> </pre>` is not working properly.

**Comment by thorade** [comment] 2015-10-14 08:55
Here is one possibility how to proceed:

@dietmarw should add @raphaelchenouard to the @modelica-tools organization,
then @raphaelchenouard can transfer ownership of the repo to @modelica-tools
That way Raphaels contributions remain visible, but the new "official" repo is not a fork (might confuse people otherwise). Transferring ownership will also transfer the issues and the wiki.

Then, once that repo exists, remove Raphael from the organization and instead add him and everybody else in this thread as collaborators to the repository so we can directly push to that repo, create branches and so on. Or create a team for that?
https://github.com/orgs/improved-permissions

Then, @lochel and @tshort can redo their pull requests to the official repo and just accept the requests themselves. 

Then, we need to fix the issues with the grammar, either by just copying my converted grammar, or by merging the two or by just fixing every single issue. 

Once we have a tested, working, official grammar, Raphael and me unpublish our Atom packages and someone (maybe Dietmar, because he has modelica-tools credentials) will publish a new Atom package.

All files used for testing should be contributed to the github linguist samples,
and the github linguist should be updated to use the new official grammar.

**Comment by dietmarw** [comment] 2015-10-14 09:08
I like to do it slightly differently.  @raphaelchenouard adds me as admin to his repo. That way I can move it to modelica-tools and add him to a new admin team for atom-language-modelica which has full access to _that_ repo.

**Comment by bilderbuchi** [comment] 2015-10-14 09:23
> Once we have a tested, working, official grammar, Raphael and me unregister our Atom packages and someone (maybe Dietmar, because he has modelica-tools credentials) registers a new Atom package.

I think the Atom folks can help with that transition, moving/repointing the URL, so that a new ugly name like `atom-language-modelica-new-official` or similar is not needed. Correct, @benogle?

**Comment by thorade** [comment] 2015-10-14 09:24
OK, but using `apm unpublish` and `apm publish` is also not too difficult.

**Comment by bilderbuchi** [comment] 2015-10-14 09:36
> OK, but using apm unpublish and apm publish is also not too difficult.

Ah, nevermind then. I witnessed that somewhere else (python autocomplete packages), where one package needed deprecation in favour of another. If the names don't stay reserved after `apm unpublish`, then all is well. :-)

**Comment by thorade** [comment] 2015-10-14 09:39
Well, I never unpublished a package, so I do not know for sure what happens. We can just try or we can ask the apm people in advance!?
So maybe I unpublish my package first as a test and we see what happens.

**Comment by bilderbuchi** [comment] 2015-10-14 09:56
OK I just checked [the docs](https://atom.io/docs/latest/behind-atom-maintaining-your-packages):
- [Ownership](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#transferring-ownership): "If you want to hand off support of your package to someone else, you can do that by transferring the package’s repository to the new owner."
- [Unpublish](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#unpublish-your-package): 
  - "It is important that you unpublish your package before deleting your repository. If you delete the repository first, you will lose access to the package and will not be able to recover it without assistance."
  - **BUT**: "Once a package name has been used, it **cannot be re-used** by another package even if the original package is unpublished."
- [Renaming](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#rename-your-package) is also possible

So, I think [transferring ownership](https://help.github.com/articles/transferring-a-repository/) of this repo from Raphael to the modelica-tools org, like @dietmarw proposed, seems to do what is desired, AFAICT.

**Comment by tshort** [comment] 2015-10-14 10:19
+1 to @dietmarw's plan.

**Comment by raphaelchenouard** [comment] 2015-10-14 11:00
So to be sure of what i have to do (i don't use github very often, it's my
1rst repo):
- I've already accepted Dietmar invitation to modelica-tools as admin of
  atom-modelica-language
- I will add Dietmar as a collaborator to my repo

That's all for me now and Dietmar will transfer the repo to modelica-tools.

Raphael.

2015-10-14 12:19 GMT+02:00 Tom Short notifications@github.com:

**Comment by thorade** [comment] 2015-10-14 11:02
Adding Dietmar as admin to this repo should be all you have to do now.
https://github.com/raphaelchenouard/atom-language-modelica/settings
Dietmar and the others will then take care of the next steps.
Thanks!

**Comment by dietmarw** [comment] 2015-10-14 11:14
@raphaelchenouard  You need to make me "owner" so I can move the repo. You should find this in the settings under https://github.com/raphaelchenouard/atom-language-modelica/settings/collaboration and there should be some option to the side of my username

**Comment by thorade** [comment] 2015-10-14 11:17
Dietmar, I am not sure about that.
Maybe Raphael has to do the transfer.

I added you also to my repo, but there is no option next to your name:
https://github.com/thorade/atom-language-modelica3/settings/collaboration

**Comment by dietmarw** [comment] 2015-10-14 11:22
@thorade Yes you are right. My bad. 
@raphaelchenouard OK here is what you do: Go to https://github.com/raphaelchenouard/atom-language-modelica/settings and scroll down to the "Danger zone". There is a "Transfer" button. Press that and transfer the  ownership to "modelica-tools". That's it.

**Comment by bilderbuchi** [comment] 2015-10-14 11:24
Owner and admin are permission levels restricted to organisation repositories, they don't exist for personal ones. @raphaelchenouard has to go to Settings - Danger Zone - Transfer ownership - Transfer, then enter the name of the repo for confirmation, and the _organisation_ name, i.e. "modelica-tools".

Edit: ah, concurrent comments. :D

**Comment by tshort** [comment] 2015-10-14 11:30
@thorade, I'm good with swapping in your grammar. It does seem to work better, and it's more concise. That Lightshow website you used for comparisons is cool. I hadn't seen that before.

**Comment by thorade** [comment] 2015-10-14 11:37
All credits for writing a working / concise grammar go to @BorisChumichev
Lightshow is used by the github linguist guys to test new grammars:
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting

**Comment by raphaelchenouard** [comment] 2015-10-14 11:43
I tried to transfer, but i think it won't work since i have not admin
rights to modelica-tools (i got this error message).

Raphael.

2015-10-14 13:37 GMT+02:00 Matthis Thorade notifications@github.com:

**Comment by thorade** [comment] 2015-10-14 11:44
Raphael, can you try to transfer it to dietmarw ?
And then dietmarw transfers it to modelica-tools ?

**Comment by dietmarw** [comment] 2015-10-14 11:52
@raphaelchenouard, @thorade and I just tested that procedure (first transfer to my @dietmarw account) and that should work.

**Comment by raphaelchenouard** [comment] 2015-10-14 14:09
Since it was not working with a transfer to modelica-tools, i transfered to
dietmarw.

Now Dietmar can do what he want.

Raphael.

2015-10-14 13:52 GMT+02:00 Dietmar Winkler notifications@github.com:

**Comment by thorade** [comment] 2015-10-14 14:12
Thank you Raphael!

**Comment by dietmarw** [comment] 2015-10-14 17:17
Transfer finished. Now I need to know who should have admin and who simply write permission.

**Comment by thorade** [comment] 2015-10-14 19:16
I do NOT need admin rights. 
Write permission is nice, but I can just as well live with forking + pull requests.

The Atom.io package is still linked to the old repo:
https://atom.io/packages/language-modelica
Do we need to do anything?

**Comment by dietmarw** [comment] 2015-10-14 19:23
I'm mainly intetested to know who should be able to accept pull requests. Now i don't mind doing this but would not be able to vouch on any qa of the PRs. I'm simply not an atom user. Emacs is my "OS".

**Comment by tshort** [comment] 2015-10-14 19:52
If admins are the only one's that can accept pull requests, then we should have multiple admins. I suggest at least @thorade, @lochel, and myself (and hopefully @raphaelchenouard if he wants).

Those with admin or write access should still use pull requests to make changes (unless it's trivial).

**Comment by lochel** [comment] 2015-10-14 20:01
@tshort Sounds like a plan!

**Comment by bilderbuchi** [comment] 2015-10-14 20:04
no, not only admins can do this. everybody with push access can merge PRs

**Comment by tshort** [comment] 2015-10-14 20:16
Hopefully, `apm publish` will fix atom.io once we're set to publish the new version.

**Comment by dietmarw** [comment] 2015-10-15 09:14
OK for safety reasons I've now given: @tshort, @thorade, @lochel, @raphaelchenouard write access. (I just had an emergency caused by someone deleting the upstream instead of the fork. Fortunately GitHub staff was awesome and all was resolved after a couple of hours during a Friday night.) Not having admin rights just saves you from this kind of mistakes. If you still need them anyway, then simply give me a shout.

**Comment by dietmarw** [comment] 2015-10-15 09:16
So I guess this issue can be closed once the atom.io entry is also update.

**Comment by thorade** [comment] 2015-10-15 09:29
I tried to publish a new version `v0.2.0` but did not succeed. Unsure about the reason, maybe because I am not an admin/owner?

**Comment by thorade** [comment] 2015-10-15 10:43
I was just doing it wrong:
`apm publish` is using git, so you have to run it from a git enabled command prompt.

If you use `apm publish minor` then apm will update the version in the package.json file, create a commit, create a git tag, and push it to the repo.

If you prefer to do some of the steps manualy, one can also use `apm publish v0.2.0` it seems.
I'll edit/correct this comment if necessary.

**Closed as completed by thorade** 2015-10-15 10:43 UTC
